name: flutter_p_shop
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  iconsax_flutter: ^1.0.0
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  url_launcher: ^6.3.1
  logger: ^2.4.0
  intl: ^0.19.0
  http: ^1.2.2
  get_storage: ^2.1.1 
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.1
  smooth_page_indicator: ^1.2.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    # - assets/icons
    - assets/images/on_boarding_images/
    - assets/images/animations/receive-email.png
    - assets/images/logo/facebook.png
    - assets/images/logo/google.png
    - assets/images/logo/t-store-light-logo.png
    - assets/images/categories/icons8-bowling-64.png
    - assets/images/categories/icons8-dummy-64.png
    - assets/images/categories/icons8-cosmetics-64.png
    - assets/images/categories/icons8-shoes-64.png
    - assets/images/categories
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

      
